AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'app/services/fetch_coffees/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
