require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/brews', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Brew. As you add validations to Brew, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Brew.create! valid_attributes
      get brews_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      brew = Brew.create! valid_attributes
      get brew_url(brew)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_brew_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      brew = Brew.create! valid_attributes
      get edit_brew_url(brew)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Brew' do
        expect do
          post brews_url, params: { brew: valid_attributes }
        end.to change(Brew, :count).by(1)
      end

      it 'redirects to the created brew' do
        post brews_url, params: { brew: valid_attributes }
        expect(response).to redirect_to(brew_url(Brew.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Brew' do
        expect do
          post brews_url, params: { brew: invalid_attributes }
        end.to change(Brew, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post brews_url, params: { brew: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested brew' do
        brew = Brew.create! valid_attributes
        patch brew_url(brew), params: { brew: new_attributes }
        brew.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the brew' do
        brew = Brew.create! valid_attributes
        patch brew_url(brew), params: { brew: new_attributes }
        brew.reload
        expect(response).to redirect_to(brew_url(brew))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        brew = Brew.create! valid_attributes
        patch brew_url(brew), params: { brew: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested brew' do
      brew = Brew.create! valid_attributes
      expect do
        delete brew_url(brew)
      end.to change(Brew, :count).by(-1)
    end

    it 'redirects to the brews list' do
      brew = Brew.create! valid_attributes
      delete brew_url(brew)
      expect(response).to redirect_to(brews_url)
    end
  end
end
