require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/coffees', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Coffee. As you add validations to Coffee, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Coffee.create! valid_attributes
      get coffees_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      coffee = Coffee.create! valid_attributes
      get coffee_url(coffee)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_coffee_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      coffee = Coffee.create! valid_attributes
      get edit_coffee_url(coffee)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Coffee' do
        expect do
          post coffees_url, params: { coffee: valid_attributes }
        end.to change(Coffee, :count).by(1)
      end

      it 'redirects to the created coffee' do
        post coffees_url, params: { coffee: valid_attributes }
        expect(response).to redirect_to(coffee_url(Coffee.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Coffee' do
        expect do
          post coffees_url, params: { coffee: invalid_attributes }
        end.to change(Coffee, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post coffees_url, params: { coffee: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested coffee' do
        coffee = Coffee.create! valid_attributes
        patch coffee_url(coffee), params: { coffee: new_attributes }
        coffee.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the coffee' do
        coffee = Coffee.create! valid_attributes
        patch coffee_url(coffee), params: { coffee: new_attributes }
        coffee.reload
        expect(response).to redirect_to(coffee_url(coffee))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        coffee = Coffee.create! valid_attributes
        patch coffee_url(coffee), params: { coffee: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested coffee' do
      coffee = Coffee.create! valid_attributes
      expect do
        delete coffee_url(coffee)
      end.to change(Coffee, :count).by(-1)
    end

    it 'redirects to the coffees list' do
      coffee = Coffee.create! valid_attributes
      delete coffee_url(coffee)
      expect(response).to redirect_to(coffees_url)
    end
  end
end
