require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/roasters", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Roaster. As you add validations to Roaster, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Roaster.create! valid_attributes
      get roasters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      roaster = Roaster.create! valid_attributes
      get roaster_url(roaster)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_roaster_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      roaster = Roaster.create! valid_attributes
      get edit_roaster_url(roaster)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Roaster" do
        expect {
          post roasters_url, params: { roaster: valid_attributes }
        }.to change(Roaster, :count).by(1)
      end

      it "redirects to the created roaster" do
        post roasters_url, params: { roaster: valid_attributes }
        expect(response).to redirect_to(roaster_url(Roaster.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Roaster" do
        expect {
          post roasters_url, params: { roaster: invalid_attributes }
        }.to change(Roaster, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post roasters_url, params: { roaster: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested roaster" do
        roaster = Roaster.create! valid_attributes
        patch roaster_url(roaster), params: { roaster: new_attributes }
        roaster.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the roaster" do
        roaster = Roaster.create! valid_attributes
        patch roaster_url(roaster), params: { roaster: new_attributes }
        roaster.reload
        expect(response).to redirect_to(roaster_url(roaster))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        roaster = Roaster.create! valid_attributes
        patch roaster_url(roaster), params: { roaster: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested roaster" do
      roaster = Roaster.create! valid_attributes
      expect {
        delete roaster_url(roaster)
      }.to change(Roaster, :count).by(-1)
    end

    it "redirects to the roasters list" do
      roaster = Roaster.create! valid_attributes
      delete roaster_url(roaster)
      expect(response).to redirect_to(roasters_url)
    end
  end
end
